services:
  ubuntu-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu_server
    hostname: ubuntu_server
    tty: true     # Keep the container running with an interactive shell
    stdin_open: true
    volumes:
      - ./user_data:/home/ubuntu
      - ../temp:/data/temp

    ports:
      - "2222:22"

    networks:
      server-network:
        ipv4_address: 172.33.0.6
  
networks:
  server-network:
    external: true
